import { LearningModule } from "@/types/learning";

export const unit2InformedSearchModule: LearningModule = {
  id: "unit-2-informed-search",
  title: "Unit 2: Informed & Heuristic Search",
  description:
    "Heuristic Search, Greedy Best-First, A* Search, Admissibility & Consistency, IDA*, Weighted A*, Hill Climbing, Simulated Annealing, and Genetic Algorithms.",
  status: "in-progress",
  tags: ["CURAJ MSc CS", "Core 1: 6.0CSC01", "CIA-1 Exam"],
  detailedContent: `# Unit 2: Informed & Heuristic Search

> **CURAJ M.Sc. Computer Science — Course Code: 6.0CSC01 (Core 1, 4 Credits)**  
> **Syllabus Coverage**: Heuristic functions $h(n)$, Greedy Best-First Search, $A^*$ Algorithm, Admissible and Consistent Heuristics, Optimality Proof of $A^*$, Memory-Bounded Heuristic Search ($IDA^*$, $SMA^*$), Local Search (Hill Climbing, Simulated Annealing, Local Beam Search, Genetic Algorithms).

---

## Unit Topics Outline

1. **Heuristics & Best-First Search**:
   - Defining heuristic evaluation functions $h(n)$.
   - Greedy Best-First Search ($f(n) = h(n)$): Incomplete in loops, non-optimal.
2. **$A^*$ Search Algorithm**:
   - Total evaluation function:
     $$f(n) = g(n) + h(n)$$
     Where $g(n)$ is actual cost from root to node $n$, and $h(n)$ is estimated cost from $n$ to the nearest goal.
3. **Conditions for Optimality**:
   - **Admissibility**: An admissible heuristic never overestimates the true cost to reach the goal:
     $$0 \le h(n) \le h^*(n), \quad \forall n$$
   - **Consistency (Monotonicity)**: For every node $n$ and every successor $n'$ generated by action $a$:
     $$h(n) \le c(n, a, n') + h(n')$$
     *(Consistent heuristics satisfy the triangle inequality and guarantee that the first time a node is expanded in graph search, its $g$-cost is optimal).*
4. **Memory-Bounded Heuristic Search**:
   - **Iterative Deepening $A^*$ ($IDA^*$)**: Cutoff is based on $f$-cost rather than depth. Space complexity $O(bd)$.
   - **Simplified Memory-Bounded $A^*$ ($SMA^*$)**: Drops highest $f$-cost node from memory when RAM limit is reached.
5. **Local Search & Optimization**:
   - **Hill-Climbing Search**: Greedy local ascent/descent; vulnerabilities to local maxima, ridges, and plateaus.
   - **Simulated Annealing**: Escapes local optima by probabilistic downhill moves governed by temperature parameter $T$:
     $$P(\text{accept}) = e^{\Delta E / T}$$
   - **Genetic Algorithms**: Population of state representations, fitness function, selection, crossover, and mutation.

---

> *Note: Comprehensive notes and CIA-1 / JRF quiz for Unit 2 are coming up for the next assessment cycle.*
`,
  practiceQuiz: [
    {
      id: "ai-u2-q1",
      question:
        "For A* search on a graph to be guaranteed optimal without reopening closed nodes, the heuristic function h(n) must be:",
      options: [
        "Admissible only",
        "Consistent (Monotonic)",
        "Strictly positive only",
        "Linear in depth",
      ],
      correctAnswer: 1,
      explanation:
        "In graph search (where duplicate states on different paths are discarded via a closed set), consistency is required to guarantee optimality without needing to reopen closed nodes.",
      difficulty: "medium",
      topicTag: "A* Optimality",
    },
  ],
};
