name: Documentation Improvement
about: Suggest an improvement to the project documentation
title: '[Docs]: '
labels: 'documentation,triage'
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve our documentation! Please provide details about the documentation issue or suggestion.
  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - README.md
        - Code Comments
        - Configuration Files
        - Setup Guide
        - API Documentation
        - Other (please specify)
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Location
      description: Where is the documentation located? (File path, URL, etc.)
      placeholder: ex. README.md, /docs/setup.md, /api/v1/users
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What is wrong with the current documentation or what needs to be added?
      placeholder: Describe the documentation issue or what needs to be added...
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve the documentation?
      placeholder: Provide your suggested changes or additions...
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue here.
    validations:
      required: false